### ISSUE TITLE
Any arxiv paper or report?

### ISSUE THREAD

**Issue by zhimin-z** [vectara/hallucination-leaderboard#24]

**Comment by amin2718** [comment]
We have a detailed write-up on the methodology employed here: [Cut the Bull…. Detecting Hallucinations in Large Language Models](https://vectara.com/blog/cut-the-bull-detecting-hallucinations-in-large-language-models/). Simon, the author, was also the lead researcher who carried out development of the model.

**Comment by TomLucidor** [comment]
Here is the question: How do you manage Qwen or Llama or DeepSeek or Gemma to halloucinate less and be on par with API models?

P.S. GLM is what CodeGeeX is based on, which is very surprising considering it has lower risk of halloucination.
