### ISSUE TITLE
Would you please provide a citation bibtex?

### ISSUE THREAD

**Issue by JacksonWuxs** [vectara/hallucination-leaderboard#26]
Hi authors! 

Definitely, it is great work! 

I am trying to reference your trained model in my research, but I cannot find a  proper Bibtex. I know there is a blog link, but it would be better if you could provide a BibTex format. 

Thanks,
Xuansheng

**Comment by amin2718** [comment]
Hi Jackson, thank you for your comments. We provide [CITATION.cff](https://github.com/vectara/hallucination-leaderboard/blob/main/CITATION.cff) which might suffice? I've tried to convert it below, but I'm not very familiar with the details of the BibTeX format.

```
@dataset{HughesBae2023,
  author       = {Simon Hughes and Minseok Bae},
  title        = {Vectara Hallucination Leaderboard},
  year         = {2023},
  month        = {11},
  publisher    = {GitHub},
  version      = {1.2.0},
  doi          = {},
  url          = {https://github.com/vectara/hallucination-leaderboard},
  abstract     = {A leaderboard comparing LLM performance at maintaining factual consistency when summarizing a set of facts.},
  keywords     = {nlp, llm, hallucination, nli, machine learning},
  license      = {Apache-2.0},
}
```

**Comment by JacksonWuxs** [comment]
Hi Simon, thanks for sharing! This works for me.
