### ISSUE TITLE
how did you determine what is factually correct ?

### ISSUE THREAD

**Issue by listaction** [vectara/hallucination-leaderboard#4]
please share details of how you determined how you came to the conclusion that something is factually correct? Did you further take the generated summary and the actual article again and ask another LLM if the summary is factually correct? If so which one was used? How do you know that was not hallucinating / accurate?

**Comment by simonhughes22** [comment]
Please see this article as well as our methodology section - https://vectara.com/cut-the-bull-detecting-hallucinations-in-large-language-models/., as well as the FAQ. It is using a model, and yes that model is not 100% perfect. Neither are humans. Any human eval would be a one off and could not be given away for others to reproduce, nor would it regularly updatable (e.g. we just added GPT 4 turbo). It is a lot easier a problem to solve to detect a hallucination than to have a general LLM that does not hallucinate. Using GPT 4 to detect hallucinations in other LLMs makes less sense, unless it's shown to be reliable at doing so.

**Comment by listaction** [comment]
thanks Simon. any chance of sharing the code to train the model ?  Summaries of statements are so subjective on context and vary in size quite a bit,  and thus its hard to draw any conclusions on "scores" of such models.
