### ISSUE TITLE
Google Palm API version?

### ISSUE THREAD

**Issue by zizhaozhang** [vectara/hallucination-leaderboard#5]
which API is used for Google Palm and Google Palm Chat?

**Comment by simonhughes22** [comment]
Please see API details where we list all this info. We used text-bison-001 model, and for Palm Chat we used chat-bison-001. There are now newer models  'in preview' in Vertex. When i tested them the chat model was much improved and at around 90%, comparable to Palm 2. But the other model was barely improved, and they are still at the bottom of the leader board (but better than the 30% hallucination rate previously). We will be updating the leaderboard with these newer numbers soon, as we have a person working on it.
